spring:
  application:
    name: MbfDataLib
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: ${DB_URL:jdbc:sqlserver://tap2pay-test-rds.cebsiv9t9ggo.ap-southeast-2.rds.amazonaws.com:1433;databaseName=YOUCLOUD;encrypt=true;trustServerCertificate=true} #;encrypt=true;trustServerCertificate=true;  #useSSL=false;
    username: ${DB_USERNAME:youcloudpay}
    password: ${DB_PASSWORD:e27gWLkvHYxW6tqc9BX4}
    hikari:
      connection-timeout: 20000 #maximum number of milliseconds that a client will wait for a connection
      maximum-pool-size: 500 #maximum pool size
      minimum-idle: 10 #minimum number of idle connections maintained by HikariCP in a connection pool
      pool-name: youcloud
      leak-detection-threshold: 30000
    jpa:
      show-sql: ${SHOW_SQL_LOCAL:true}
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
  profiles:
    group:
      "dev": datasource-dev,error-msg,mpos,tiny-log

server:
  port: ${SERVER_PORT:8088}
  servlet:
    contextPath: /mbf
  error:
    path: /error
    whitelabel:
      enabled: false

#springdoc:
#  packagesToScan:
#    - "com.youcloud.middleware"
#  swagger-ui:
#    path: /aus-pos-mv-swagger-ui.html
#  api-docs:
#    path: /api-docs


management:
  endpoints:
    enabled-by-default: ${IS_ENABLED_MANAGEMENT_ENDPOINTS:false}
    web:
      exposure:
        include: ${INCLUDED_MANAGEMENT_ENDPOINTS:*}

logging:
  level:
    com:
      youcloud:
        mbf: DEBUG