package com.youcloud.mbf.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.youcloud.mbf.common.util.DateUtil;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.extern.jackson.Jacksonized;
import lombok.extern.slf4j.Slf4j;

import static com.youcloud.mbf.common.constant.MbfFileConstant.EXTENSION;
import static com.youcloud.mbf.common.constant.MbfFileConstant.TPP_IDENTIFIER;
import static com.youcloud.mbf.common.constant.MbfFileConstant.VERSION;

@Slf4j
@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)
@Jacksonized
public class MbfFileName {

    /**
     * Position 1 to 8 (8 chars)
     */
    @Builder.Default
    private String jobId = "TT4220MB"; //JobId jobId;

    /**
     * Two character short description of the file.
     * This will be a constant value as “MD”, i.e. Merchant Disbursement.
     *
     * Position 9 to 10 (2 chars)
     */
    @Builder.Default
    private String fileDescriptionShort = "MBF";

    /**
     * Acquirer ID configured in Fiserv systems. This will be a constant value as “021”.
     *
     * Position 11 to 13 (3 chars)
     */
    @Builder.Default
    private String acquirerId = "021";

    /**
     * TPP ID configured in Fiserv systems.
     * This will vary for each TPP and Fiserv will communicate with each TPP during enablement.
     *
     * Position 14 to 16 (3 chars)
     */
    @Builder.Default
    private String tppIdentifier = TPP_IDENTIFIER;

    /**
     * This will be set to a constant value of “DE”, i.e. Direct Entry.
     *
     * Position 17 to 18 (2 chars)
     */
    /*@Builder.Default
    private String fileType = "DE";*/

    public String getFileTransmissionDate() {
        return DateUtil.getCurrentDayInYYMMDD();
    }

    /**
     * Date when the file is generated by TPP in YYMMDD format.
     *
     * Position 19 to 24 (6 chars)
     */
    @Builder.Default
    private String fileTransmissionDate = DateUtil.getCurrentDayInYYMMDD();

    /**
     * Sequence number of the file, with acceptable values from 0 to 9,
     * however, in exceptional scenario’s TPP can submit additional files as per their requirements
     */
    @Builder.Default
    private Character version = VERSION;

    /**
     * Extension “csv” Extension for the file
     * Where “.csv” indicates a csv file
     */
    @Builder.Default
    private String extension = EXTENSION;

    @Override
    public String toString() {
        return jobId + "." + fileDescriptionShort + "_" + acquirerId + "_" + tppIdentifier + "_" /*+ fileType*/ +
                fileTransmissionDate + "_" + version + "." + EXTENSION;
    }
}

